### ISSUE TITLE
Megameter vs millimeter

### ISSUE THREAD

**Issue by surbitron** [WoLpH/alfred-converter#15]
This is s really useful plug-in - well done.  I have a request regarding Megameters and millimetres.   In version 2.0 if we enter a length in millimeters (mm) the plug-in thinks we are talking Megameters (Mm).

1 millimeters (mm) = 0.001 meters
1 megameter (Mm) = 1,000,000 meters

Can you please fix this so that  'mm' translates to millimeters and 'Mm' translates to megameter, in much the way as you have for bits (b) and Bytes (B)?  Many thanks.

**Comment by surbitron** [comment]
Scrub that - Sorry for the noise!

**Comment by WoLpH** [comment]
It would be possible to fix the sorting of the results but that's often not too convenient  since it depends on your use-case. So currently the sorting is decided by alfred which means you can easily change it yourself :)

Simply select the result with the millimeter a few times (enter 1mm or so and press enter on the mm conversion you prefer) and Alfred will teach itself :)

**Comment by surbitron** [comment]
Yes, I realised my mistake almost immediately after posting.  Thanks for the swift response!

**Comment by Dilapidus** [comment]
But the only things you will see when you put 1mm into the alfred search box are things that start with 1 Megameter.     There are lots of them (dozens).   But there is nothing like 1 mm = blah blah

**Comment by WoLpH** [comment]
Initially, yes. Unfortunately I don't think I can influence the sorting that Alfred does (except completely overriding it) and the auto prioritizing system of Alfred is actually very convenient in many cases.

Once you've selected millimeter out of all of the options once or twice, it will show those first the next time.

**Comment by Dilapidus** [comment]
"Once you've selected ..."   I don't think I can.  That's what I was trying to say.  There is not one item on the list that starts with 1 mm.

**Comment by Dilapidus** [comment]
Sorry...  to be perfectly clear:   When I type "1 mm" into Alfred, I get a couple dozen (at least) options, each and every one of which starts with "1 Megameter = "  so there is no "1 Millimeter = " option for me get pushed to the top of alfred's stack.  

![image](https://user-images.githubusercontent.com/11336161/56002579-da9b8680-5c77-11e9-8aca-d9c827f71dc7.png)

 As you can see, it does  seem to be doing the right thing numerically when use it.   It just seems to call Millimeters Megameters.

**Comment by WoLpH** [comment]
You found a bug indeed @Dilapidus, when there are 2 units with the same annotation but only a case difference it was non-deterministic which order was used. Since the results are cached though, it effectively resulted in some people not being able to use millimeter.

I've fixed the bug so it initially attempts the exact case, if that fails it will fall back to case insensitive searches.

Can you give it a try? :)

**Comment by Dilapidus** [comment]
![image](https://user-images.githubusercontent.com/11336161/56335463-6bc79d00-6151-11e9-9e98-7b121f225c71.png)

Much better, thanks!   I still wonder that 1mm = 1 Megameter but that's ok, I had never heard of a megameter before this.

**Comment by WoLpH** [comment]
Yeah, that's definitely wrong. I think it must be some kind of overflow somehow but I haven't been able to track down the cause.

**Comment by Dilapidus** [comment]
I promise you I will never care :-)
