### ISSUE TITLE
Different spellings

### ISSUE THREAD

**Issue by tiredAcademic** [WoLpH/alfred-converter#2]
Request support for the following:

 - US spelling of Liter

 - m^3 is supported but metre^3 or meter^3 is not

Can you do options? it would be nice to choose -re or -er endings for SI units.

**Comment by WoLpH** [comment]
Well, the thing is. I'm using the `poscUnits22.xml` file which I just found by Googling to be honest (url: http://w3.energistics.org/uom/poscUnits22.xml). And it uses English instead of US spelling by default which makes displaying something different slightly tricky.

I've added some new aliases and changed the default output to show us-style measures. There appears to be no easy and fast way to do language detection from Python in OS X so it's just default to US now :)

Please give it a try, you can download the zip here: https://github.com/WoLpH/alfred-converter/archive/master.zip and overwrite the files in your current workflow folder. Note that for the best effect you should remove the `units.pickle` file, it automatically gets re-generated but it might cache the old units.

**Comment by tiredAcademic** [comment]
Alright I'll take a look, thanks for getting my back so quickly.
