### ISSUE TITLE
Not working since Python2 removed by MacOS 12.3+

### ISSUE THREAD

**Issue by LunarRed** [WoLpH/alfred-converter#39]
MacOS 12.3+ completely removes Python 2 (https://www.jamf.com/blog/python2-is-gone-apple-macos/) and converter no longer works. Get message: "Reason: launch path not accessible /usr/bin/python" "Check that the selected language exists on your system."

**Comment by WoLpH** [comment]
The silly thing is... Alfred doesn't appear to have Python 3 support from what I can gather. Although that might be because I'm not using OS X 12.3

Fixing the script properly is harder due to lack of support from Alfred:
<img width="301" alt="image" src="https://user-images.githubusercontent.com/270571/163892237-a7261518-1a18-4569-900c-eb49eec05fc7.png">

I'm working on a new release :)

**Comment by LunarRed** [comment]
Unfortunately, once you upgrade to 12.3, you get this:

<img width="520" alt="Screen Shot 2022-04-18 at 5 14 12 PM" src="https://user-images.githubusercontent.com/3605985/163896179-cbcd6eda-4316-4a07-b46d-5f4dfd737ac4.png">

Then, I installed Python 2 using this: https://www.alfredapp.com/help/kb/python-2-monterey/, but it still wants to use the Python from the path `/usr/bin/python`, and I can't/shouldn't create it there because of SIP protection.

**Comment by WoLpH** [comment]
I've created a new version that should work, can you try? https://github.com/WoLpH/alfred-converter/blob/master/unit_converter.alfredworkflow

**Comment by LunarRed** [comment]
Yes, that new version works great. Thank you for getting a fix out so quickly!
