### ISSUE TITLE
Would be nice to be able to do simple math

### ISSUE THREAD

**Issue by videopilot** [WoLpH/alfred-converter#43]
For example:

(1314.65 * 3) mm to in

Just because I often have to jump back to the main Alfred calculator, copy the result, and then open again to plug that into the conversion.

**Comment by WoLpH** [comment]
The issue here is actually with the parentheses because this is supported out of the box. To illustrate:

<img width="766" alt="image" src="https://user-images.githubusercontent.com/270571/196818482-e158bc9f-8ca3-4908-be87-635188da0276.png">

But I suppose it should be possible to get it working with the parentheses as well. The short story is... simple multiplications/additions get simplified to a single number so typing `10 + 20 x` automatically collapses to `30 x` internally. But when you add parentheses it goes into math mode which also supports functions such as sine/cosine/etc. and in that mode it does not look at units anymore

**Comment by WoLpH** [comment]
The new version now also supports calculations for units:

<img width="766" alt="image" src="https://user-images.githubusercontent.com/270571/196821782-7cabdf89-dd95-493f-946e-64c488960eee.png">

<img width="766" alt="image" src="https://user-images.githubusercontent.com/270571/196821887-8964ed58-5210-4747-a3a1-b30af4f4815f.png">
